### PR TITLE
Fix TXID display formatting to use proper hex format

### LINKED ISSUE #672: Fix TXID display formatting to use proper hex format
## Description

TXID values are not displaying in the proper hex format in CLI commands. They should be displayed using `ltx.TXID.String()` which formats as `%016x`.

## Current Behavior

TXIDs are displaying as decimal strings like:
```
30303030303030303030303030303032
```

## Expected Behavior

TXIDs should display as 16-character hex strings like:
```
0000000000000002
```

## Example Output

Current output from `litestream wal` command:
```
$ ./litestream wal s3://litestream-test.localhost:9000/test-db
min_txid                          max_txid  size  created
30303030303030303030303030303032  2         422   2025-07-30T23:22:36Z
```

Expected output:
```
$ ./litestream wal s3://litestream-test.localhost:9000/test-db
min_txid          max_txid          size  created
0000000000000002  0000000000000002  422   2025-07-30T23:22:36Z
```

## Implementation Details

- Update all CLI commands to display TXID using `ltx.TXID.String()`
- This method formats the TXID as `%016x` (16-character hex string)
- Ensure consistent formatting across all commands that display TXIDs

## Affected Commands

- `litestream wal` (soon to be `ltx`)
- Any other commands that display transaction IDs

## Screenshot

\TXID Formatting Issue

## Additional Context

This formatting issue was identified by Ben Johnson during review of the v0.5.0-beta1 implementation.

### PR DESCRIPTION
**Pull request by corylanou**
## Summary

This PR fixes the TXID display formatting issue reported in #672. The transaction IDs were displaying inconsistently - sometimes as variable-length hex values and sometimes as decimals.

## Changes

- Changed format verbs from `%x` and `%d` to `%s` for TXID values in `cmd/litestream/ltx.go`
- The `%s` format verb automatically calls the TXID's `.String()` method, which formats as `%016x` (16-character zero-padded hexadecimal)
- Added a test to verify that `TXID.String()` produces the correct format

## Result

Transaction IDs now consistently display as 16-character hexadecimal strings (e.g., `0000000000000001` instead of `1`), making them easier to read and compare.

## Testing

Added `TestTXIDString` to verify the formatting behavior.

Fixes #672

### CODE REVIEW

File: cmd/litestream/ltx_test.go [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+			if result != tt.expected {
+				t.Errorf("TXID(%x).String() = %s, want %s", uint64(tt.txid), result, tt.expected)
+			}
+			// Verify it's always 16 characters
+			if len(result) != 16 {
+				t.Errorf("TXID string should always be 16 characters, got %d", len(result))
+			}
+		})
+	}
+}
```
Comment (benbjohnson) [inline cmd/litestream/ltx_test.go]: You can drop the unit tests. The formatting is already tested in the LTX repo.

**Review by benbjohnson — CHANGES_REQUESTED** [review]
