### PR TITLE
fix: preserve replica position after restore to prevent data loss

### LINKED ISSUE #781: Restore does not update LTX ID information
## Bug Description

The `restore` command does not restore LTX ID information which causes `replicate` to start from 0 and not backup any data until the new LTX ID exceeds the previous high-water mark.

## Environment

**Litestream version:**

```text
0.5.0
```

**Operating system & version:**

macOS 15.6.1
AlmaLinux 10
Fedora 42

**Installation method:**

Binary download, built from source, and RPMs

**Storage backend:**

File and S3

## Steps to Reproduce

1. `sqlite3 /tmp/db.sqlite "CREATE TABLE test(col1);"`
2. `litestream replicate /tmp/db.sqlite file:///tmp/backup` (Run this in a separate terminal)
3. `sqlite3 /tmp/db.sqlite "INSERT INTO test VALUES (1);"`
4. `sqlite3 /tmp/db.sqlite "SELECT * FROM test;"` (Expect "1")
5. Kill `litestream` process
6. `rm -rf /tmp/db.sqlite* /tmp/.db.sqlite-litestream` (Simulates a hard recovery scenario)
7. `litestream restore -o /tmp/db.sqlite* file:///tmp/backup`
8. `sqlite3 /tmp/db.sqlite "SELECT * FROM test;"` (Expect "1")
9. `litestream replicate /tmp/db.sqlite file:///tmp/backup` (Run this in a separate terminal)
10. `sqlite3 /tmp/db.sqlite "INSERT INTO test VALUES (2);"` (**Note:** The first sign of a problem begins here as no L0 compaction notices ever occur)
11. `sqlite3 /tmp/db.sqlite "SELECT * FROM test;"` (Expect "1 2").
12. Kill `litestream` process
13. `rm -rf /tmp/db.sqlite* /tmp/.db.sqlite-litestream` (Simulates a second hard recovery scenario)
14. `litestream restore -o /tmp/db.sqlite* file:///tmp/backup`
15. `sqlite3 /tmp/db.sqlite "SELECT * FROM test;"` (Expect "1 2" but get "1").

**Expected behavior:**

Expect the observed insert of "2" to be backed up and persisted across a restore.

**Actual behavior:**

The write of "2" is lost.  If after the first restore you continue to run long enough that the LTX ID exceeds the previous high-water mark, then you will start seeing compaction logs again and the backups proceed as expected.

## Configuration

<details><summary>litestream.yml</summary>

```yaml
access-key-id:     {{ .S3_ID }}
secret-access-key: {{ .S3_KEY }}
logging:
  level: info
dbs:
  - path: /tmp/db.sqlite
    replicas:
      - type: s3
        endpoint: https://s3.example.com
        bucket: pocket
        path: database
        region: garage
        sync-interval: 1m
        retention: 24h
```

</details>

## Logs

<details><summary>Log output</summary>

First `replicate`:

```text
time=2025-10-05T17:38:20.080-04:00 level=INFO msg=litestream version="(development build)" level=""
time=2025-10-05T17:38:20.080-04:00 level=INFO msg="initialized db" path=/tmp/db.sqlite
time=2025-10-05T17:38:20.080-04:00 level=INFO msg="replicating to" type=file sync-interval=1s path=/tmp/db.bak
time=2025-10-05T17:38:20.080-04:00 level=INFO msg="starting compaction monitor" level=9 interval=24h0m0s
time=2025-10-05T17:38:20.080-04:00 level=INFO msg="starting compaction monitor" level=3 interval=1h0m0s
time=2025-10-05T17:38:20.080-04:00 level=INFO msg="starting compaction monitor" level=1 interval=30s
time=2025-10-05T17:38:20.080-04:00 level=ERROR msg="compaction failed" level=9 error="page size not initialized yet"
time=2025-10-05T17:38:20.080-04:00 level=INFO msg="starting compaction monitor" level=2 interval=5m0s
time=2025-10-05T17:38:20.086-04:00 level=INFO msg="compaction complete" level=2 txid.min=0000000000000001 txid.max=0000000000000002 size=647
time=2025-10-05T17:39:30.010-04:00 level=INFO msg="deleting ltx file" db=db.sqlite level=0 minTXID=0000000000000002 maxTXID=0000000000000002
time=2025-10-05T17:39:30.010-04:00 level=INFO msg="deleting ltx file" db=db.sqlite level=0 minTXID=0000000000000003 maxTXID=0000000000000003
time=2025-10-05T17:39:30.010-04:00 level=INFO msg="compaction complete" level=1 txid.min=0000000000000003 txid.max=0000000000000004 size=237
^Ctime=2025-10-05T17:39:48.583-04:00 level=INFO msg="signal received, litestream shutting down"
time=2025-10-05T17:39:48.586-04:00 level=ERROR msg="failed to close database" error="sql: transaction has already been committed or rolled back"
```

Second `replicate`:

```text
time=2025-10-05T17:43:51.752-04:00 level=INFO msg=litestream version="(development build)" level=""
time=2025-10-05T17:43:51.752-04:00 level=INFO msg="initialized db" path=/tmp/db.sqlite
time=2025-10-05T17:43:51.752-04:00 level=INFO msg="replicating to" type=file sync-interval=1s path=/tmp/db.bak
time=2025-10-05T17:43:51.752-04:00 level=INFO msg="starting compaction monitor" level=9 interval=24h0m0s
time=2025-10-05T17:43:51.752-04:00 level=INFO msg="starting compaction monitor" level=1 interval=30s
time=2025-10-05T17:43:51.752-04:00 level=INFO msg="starting compaction monitor" level=3 interval=1h0m0s
time=2025-10-05T17:43:51.752-04:00 level=INFO msg="starting compaction monitor" level=2 interval=5m0s
time=2025-10-05T17:43:51.752-04:00 level=ERROR msg="compaction failed" level=9 error="page size not initialized yet"
^Ctime=2025-10-05T17:43:56.861-04:00 level=INFO msg="signal received, litestream shutting down"
time=2025-10-05T17:43:56.865-04:00 level=ERROR msg="failed to close database" error="sql: transaction has already been committed or rolled back"
```

</details>

## Additional Context

While heavy handed, clearing out the backup directory (ie, moving the backup directory or using a different S3 prefix) before starting `replicate` does allow backups to continue as expected.

### PR DESCRIPTION
**Pull request by corylanou**
## Summary

Fixes #781 - Restored databases now correctly continue replication when the replica has a higher TXID than the database.

## Problem

When a database is restored from backup and the replica has a higher TXID (e.g., after deleting the local `.litestream` directory), new writes were not replicated until the database TXID exceeded the previous high-water mark. This caused data loss.

**Example scenario:**
1. Database at TXID 5, replica at TXID 5 ✅
2. Delete local `.litestream` directory, restore from backup
3. Database at TXID 5, replica at TXID 5, but local L0 files are missing
4. Insert new data → database at TXID 6
5. **BUG**: New data not replicated because replica still thinks it's at TXID 5

## Solution

Detection happens in `DB.init()` before `replica.Start()`:

1. **Compare positions**: Database TXID vs Replica TXID
2. **Detect mismatch**: If database < replica, we have a restore scenario
3. **Fetch baseline**: Download latest L0 file from replica
4. **Trigger snapshot**: Next `DB.sync()` detects the mismatch via existing `verify()` logic and creates a snapshot

### Why This Approach Works

The fix establishes a proper baseline by fetching the latest L0 file from the replica. This allows the existing verification and snapshot mechanisms in `DB.verify()` to detect the state mismatch and trigger a snapshot automatically—no special flags or modified sync logic needed.

**Key architectural decision:** Database state validation belongs in the DB layer, not the Replica layer. This keeps the Replica focused on replication concerns only.

### `db.go`
- Added `checkDatabaseBehindReplica()` method called from `DB.init()`
- Compares database position vs replica position
- Fetches latest L0 LTX file from replica when database is behind
- Leverages existing snapshot triggering in `verify()`

### `replica.go`
- Removed `skipCalcPos` flag and related complexity
- Removed `checkReplicaPosition()`, `hasLocalL0Files()`, `clearLocalL0Files()` methods
- Simplified `Sync()` back to original logic

### `replica_test.go`
- Updated test comments to reflect new implementation approach
- Test verifies behavior transparently through `DB.init()`

## Testing

The test `TestReplica_RestoreAndReplicateAfterDataLoss` verifies the fix:

```
✅ Detected database behind replica (db_txid=0 vs replica_txid=1)
✅ Fetched latest L0 file from replica  
✅ Triggered snapshot on next sync
✅ New data successfully replicated
```

All existing tests pass, confirming no regressions.

## Benefits of This Approach

1. **Cleaner architecture**: DB state concerns in DB layer, not Replica layer
2. **Uses existing mechanisms**: Leverages `verify()` for snapshot detection
3. **No special flags**: Removed `skipCalcPos` complexity
4. **More precise detection**: Compares actual positions, not file existence
5. **Handles all restore scenarios**: Works regardless of how restore occurred

### CODE REVIEW

**Comment by benbjohnson** [comment]
@corylanou I don't think we want this in the `Replica.Sync()` code. In my mind, we'd do this check on startup:

1. In `DB.init()`, before `replica.Start()` is called, we should check if the `DB.pos` is less than `Replica.pos`.
2. If so, we should clear the local L0 files & we should fetch the latest L0 LTX file from the replica and write it to the local L0 directory.

I *think* that should be enough to trigger Litestream to issue a new L0 snapshot on its next `DB.sync()`.

File: db.go [hunk 1]
```diff
@@ -449,6 +449,15 @@ func (db *DB) init(ctx context.Context) (err error) {
...
 
+	// Check if database is behind replica (issue #781).
+	// This must happen before replica.Start() to detect restore scenarios.
+	if db.Replica != nil {
+		if err := db.checkDatabaseBehindReplica(ctx); err != nil {
+			db.Logger.Error("failed to check database position vs replica", "error", err)
+			// Continue despite error to allow normal replication
+		}
+	}
+
```
Comment (benbjohnson) [inline db.go:459]: We should probably return an error rather than continuing on.

File: db.go [hunk 2]
```diff
@@ -645,6 +654,79 @@ func (db *DB) ensureWALExists(ctx context.Context) (err error) {
...
+	minTXID, maxTXID := replicaInfo.MinTXID, replicaInfo.MaxTXID
+	reader, err := db.Replica.Client.OpenLTXFile(ctx, 0, minTXID, maxTXID, 0, 0)
+	if err != nil {
+		return fmt.Errorf("open remote L0 file: %w", err)
+	}
+	defer func() {
+		if closer, ok := reader.(io.Closer); ok {
+			_ = closer.Close()
+		}
+	}()
```
Comment (benbjohnson) [inline db.go]: `reader` is guaranteed to be an `io.Closer` since it's a `io.ReadCloser`. You don't need to do the type assertion.

File: db.go [hunk 3]
```diff
@@ -645,6 +654,79 @@ func (db *DB) ensureWALExists(ctx context.Context) (err error) {
...
+		return fmt.Errorf("create local L0 file: %w", err)
+	}
+	defer func() { _ = localFile.Close() }()
+
+	if _, err := io.Copy(localFile, reader); err != nil {
+		return fmt.Errorf("copy L0 file: %w", err)
+	}
+	if err := localFile.Sync(); err != nil {
+		return fmt.Errorf("sync L0 file: %w", err)
+	}
```
Comment (benbjohnson) [inline db.go]: Write this to a temp file (e.g. `localPath + ".tmp"`) and then rename it after syncing & closing. That way we don't have to worry about partially written files.

There's a bunch of examples of atomic file writing in Litestream (e.g. https://github.com/benbjohnson/litestream/blob/main/db.go#L912-L922)

**Comment by corylanou** [comment]
✅ Addressed in commit 4b9b050:

1. **Return error instead of continuing** - Now returns error from `checkDatabaseBehindReplica()` in db.go:456
2. **Removed unnecessary type assertion** - Simplified to direct `reader.Close()` in db.go:701  
3. **Atomic file writing** - Using temp file + rename pattern in db.go:703-730

All three review comments have been addressed. Ready for re-review! 🎉
